name: Run on PR

on:
  pull_request:
    types:
      - opened
      - closed
      - reopened
      - synchronize
      - labeled

  push:
    branches:
      - main
      - 'releases/*'
  workflow_dispatch:

permissions:
  checks: read
  contents: read
  pull-requests: write

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    name: Run unit tests
    steps:
    - uses: actions/checkout@v4
    - run: npm ci
    - run: npm test

  verify:
    runs-on: ubuntu-latest
    name: Verify PR template
    steps:
    - uses: actions/checkout@v4
    - run: npm ci
    - uses: ./
      id: extract

    - name: Fail poor parsing
      if: ${{ steps.extract.outputs.pr_pass != 'true' }}
      run: exit 1

    - name: Version successful builds
      uses: tomfreeman/sem-vpr@v1
      if: ${{ success() &&  !steps.extract.outputs.pr_release_skip }}
